// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94qVs7Z9asrVG4wD73N95yG-055vB3qk',
    appId: '1:479308506065:web:3677eda3f2e2416a3836f0',
    messagingSenderId: '479308506065',
    projectId: 'masprogramming1',
    authDomain: 'masprogramming1.firebaseapp.com',
    storageBucket: 'masprogramming1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMPzTWIOTFPk0vtUijRh_szxAkgceH6Yg',
    appId: '1:479308506065:android:1efd053d3273526e3836f0',
    messagingSenderId: '479308506065',
    projectId: 'masprogramming1',
    storageBucket: 'masprogramming1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXR4X6PKoUNixGzfcFZ5N1DEzn1F8-5pw',
    appId: '1:479308506065:ios:ad56053b5eaea3eb3836f0',
    messagingSenderId: '479308506065',
    projectId: 'masprogramming1',
    storageBucket: 'masprogramming1.appspot.com',
    iosBundleId: 'com.example.masProgramming1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXR4X6PKoUNixGzfcFZ5N1DEzn1F8-5pw',
    appId: '1:479308506065:ios:a18830f4b55f015c3836f0',
    messagingSenderId: '479308506065',
    projectId: 'masprogramming1',
    storageBucket: 'masprogramming1.appspot.com',
    iosBundleId: 'com.example.masProgramming1.RunnerTests',
  );
}
